[swipe.commands.three]
left_up = ""
right_up = ""
up = "sigdwm 'view ui 0'"
left_down = ""
right_down = ""
down = "sigdwm 'fclv i 0'"
left = "sigdwm 'sfvw i -1'"
right = "sigdwm 'sfvw i +1'"

[swipe.commands.four]
left_up = ""
right_up = ""
up = "sigdwm 'fcsk i -1'"
left_down = ""
right_down = ""
down = "sigdwm 'fcsk i +1'"
left = "sigdwm 'sftg i -1'"
right = "sigdwm 'sftg i +1'"

[pinch.commands]
in = ""
out = ""

[pinch.settings]
threshold = 0.25
one_shot = false


[swipe.settings]
threshold = 0.5
one_shot = true
trigger_on_release = false
