#!/bin/bash
case "$1" in
    e)
        xargs setsid -f gthumb
        ;;
    E)
        xargs setsid -f gimp
        ;;
    r)
        mapfile -t files
        mogrify -rotate +90 -- "${files[@]}"
        ;;
    R)
        mapfile -t files
        mogrify -rotate -90 -- "${files[@]}"
        ;;
    bar)
        mapfile -t files
        mogrify -flop -- "${files[@]}"
        ;;
    underscore)
        mapfile -t files
        mogrify -flip -- "${files[@]}"
        ;;
    w)
        IFS='' read -r file
        /home/ashish/.config/sxiv/exec/wallpaper.sh "$file"
        ;;
    d)
        mapfile -t files
        [[ "$(echo -e "Yes\nNo" | dmenu -i -p "Do you really want to delete the selected image(s)?")" == Yes ]] &&
            if rm -f -- "${files[@]}" ; then
                notify-send -t 1000 Sxiv "Deletion successful"
            else
                notify-send -u critical Sxiv "Deletion failed"
            fi
        ;;
    y)
        while IFS='' read -r file ; do
            paths="$paths $(printf %q "$(realpath -s "$file")")"
        done
        paths="${paths# }"
        if echo -n "$paths" | xsel -ib ; then
            notify-send -t 1000 Sxiv "Yank successful"
        else
            notify-send -u critical Sxiv "Yank failed"
        fi
        ;;
    Y)
        while IFS='' read -r file ; do
            paths="$paths $(printf %q "$(realpath "$file")")"
        done
        paths="${paths# }"
        if echo -n "$paths" | xsel -ib ; then
            notify-send -t 1000 Sxiv "Yank successful"
        else
            notify-send -u critical Sxiv "Yank failed"
        fi
        ;;
esac
