#!/bin/bash
case $1 in
    w)
        read -r file
        /home/ashish/.config/sxiv/exec/wallpaper.sh "$file"
        ;;
    y)
        mapfile -t files
        echo "${files[@]}" | xclip -selection clipboard &&
            notify-send "Sxiv" "Yank successful"
        ;;
    Y)
        mapfile -t files
        mapfile -t resolved_files < <(readlink -f "${files[@]}")
        echo "${resolved_files[@]}" | xclip -selection clipboard &&
            notify-send "Sxiv" "Yank successful"
        ;;
    r)
        mapfile -t files
        mogrify -rotate 90 "${files[@]}"
        ;;
    R)
        mapfile -t files
        mogrify -rotate -90 "${files[@]}"
        ;;
    f)
        mapfile -t files
        mogrify -flop "${files[@]}"
        ;;
    g)
        xargs setsid -f gimp
        ;;
    s)
        xargs setsid -f shotwell
        ;;
    d)
        mapfile -t files
        [ "$(echo -e "Yes\nNo" | dmenu -i -p "Do you really want to delete the selected image(s)?")" = Yes ] &&
            rm -f "${files[@]}" &&
                notify-send "Sxiv" "Deletion successful"
        ;;
esac
