#!/bin/bash
case $1 in
    w)
        read -r file
        /home/ashish/.config/sxiv/exec/wallpaper.sh "$file"
        ;;
    y)
        pwd=$(pwd)
        while read -r file ; do
            paths="$paths $(printf %q "$pwd/$file")"
        done
        paths=${paths# }
        if echo -n "$paths" | xclip -selection clipboard ; then
            notify-send -t 1000 Sxiv "Yank successful"
        else
            notify-send -u critical Sxiv "Yank failed"
        fi
        ;;
    Y)
        while read -r file ; do
            paths="$paths $(printf %q "$(realpath "$file")")"
        done
        paths=${paths# }
        if echo -n "$paths" | xclip -selection clipboard ; then
            notify-send -t 1000 Sxiv "Yank successful"
        else
            notify-send -u critical Sxiv "Yank failed"
        fi
        ;;
    r)
        mapfile -t files
        mogrify -rotate 90 "${files[@]}"
        ;;
    R)
        mapfile -t files
        mogrify -rotate -90 "${files[@]}"
        ;;
    f)
        mapfile -t files
        mogrify -flop "${files[@]}"
        ;;
    g)
        xargs setsid -f gimp
        ;;
    s)
        xargs setsid -f shotwell
        ;;
    d)
        mapfile -t files
        [[ $(echo -e "Yes\nNo" | dmenu -i -p "Do you really want to delete the selected image(s)?") = Yes ]] &&
            if rm -f "${files[@]}" ; then
                notify-send -t 1000 Sxiv "Deletion successful"
            else
                notify-send -u critical Sxiv "Deletion failed"
            fi
        ;;
esac
