#!/bin/dash
while read file
do
        case "$1" in
        "w")
                /home/ashish/.config/sxiv/exec/wallpaper.sh "$file" ;;
	"r")
		convert -rotate 90 "$file" "$file" ;;
	"R")
		convert -rotate -90 "$file" "$file" ;;
	"f")
		convert -flop "$file" "$file" ;;
	"y")
		echo -n "$file" | xclip -selection clipboard &&
		notify-send "$file copied to clipboard" & ;;
	"Y")
		readlink -f "$file" | xclip -selection clipboard &&
			notify-send "$(readlink -f "$file") copied to clipboard" & ;;
	"d")
		[ "$(echo "No\\nYes" | dmenu -i -p "Do you really want to delete $file")" = "Yes" ] && rm -f "$file" && notify-send "$file deleted" ;;
	"g")
                gimp "$file" & ;;
        "n")
                nomacs "$file" & ;;
        esac
done
